### ISSUE TITLE
Caching tasks

### ISSUE THREAD

**Issue by frozzare** [frozzare/max#1]
Some type of caching of tasks would be nice to know if they are up to date or not.

**Comment by frozzare** [comment]
This can be solved with `status` commands:

```
tasks:
  build:
    summary: "Build task"
    status:
      - test -e main
    commands:
      - go build main.go
```
